[package]
name = "litebox_platform_macos_userland"
version = "0.1.0"
edition = "2024"

[target.'cfg(all(target_os = "macos", target_arch = "aarch64"))'.dependencies]
litebox_platform = { path = "../litebox_platform", version = "0.1.0" }
litebox = { path = "../litebox", version = "0.1.0" }
litebox_common_linux = { path = "../litebox_common_linux", version = "0.1.0", features = ["aarch64_gate_recovery"] }
libc = { version = "0.2.169", default-features = false }
litebox_syscall_rewriter = { path = "../litebox_syscall_rewriter", version = "0.1.0", default-features = false }
zerocopy = { version = "0.8", default-features = false }

[lints]
workspace = true
